servers:
  - name: "Istanbul Agency"
    url: "http://localhost:3000"
    distance_km: 10
  - name: "Paris Agency"
    url: "http://localhost:3001"
    distance_km: 2005
  - name: "New York Agency"
    url: "http://localhost:3002"
    distance_km: 8000
  - name: "Tokyo Agency"
    url: "http://localhost:3003"
    distance_km: 9000
  - name: "Sydney Agency"
    url: "http://localhost:3004"
    distance_km: 15000
  - name: "Moscow Agency"
    url: "http://localhost:3005"
    distance_km: 3000
  - name: "Cape Town Agency"
    url: "http://localhost:3006"
    distance_km: 8000
